[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=1.11.2"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.11.0"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.2"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "1.0.0"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.4"
